config/routes.rb
Rails.application.routes.draw do

  devise_for :pharmacies, :controllers => { :registrations => "authentication/pharmacies/registrations" }
  devise_scope :pharmacy do
    get '/pharmacy/login', to: 'devise/sessions#new'
    get '/pharmacy/registration', to: 'devise/registrations#new'
    get '/password/settings', to: 'authentication/pharmacies/registrations#edit'
    get '/retrieve/password', to: 'devise/passwords#new'
  end
  authenticated :pharmacy do
    root 'main/pharmacies#dashboard', as: :authenticated_pharmacy_root
  end
  
  scope module: "main" do
    get '/check-status', to: 'patients#check_status'
    get '/request-refill', to: 'patients#request_refill'
    get '/patients', to: 'patients#patients'
    get '/getting-started', to: 'pages#getting_started'
    get '/patient/dashboard', to: 'patients#dashboard'
    
    get '/pharmacy/settings', to: 'pharmacies#edit'
    get '/pharmacy/dashboard', to: 'pharmacies#dashboard'
    get '/requests/status', to: 'pharmacies#status_requests'
    get '/requests/refill', to: 'pharmacies#refill_requests'
    post '/update_rx_status', to: 'pharmacies#update_rx_status'
    get '/load_chart', to: 'pharmacies#load_chart'
  end
  
  namespace :api do
    post '/twilio_trigger', to: 'central#twilio_trigger'
    post '/twilio_trigger_callback', to: 'central#twilio_trigger'
    post '/save_subscription', to: 'central#save_subscription'
  end
  
  namespace :simulator do
    get '/', to: 'testing#home'
  end
  
  resources :pharmacies, except: :index
  root 'main/pages#home'
  
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :patient_alerts
end

app/controllers/authentication/pharmacies/registrations_controller.rb
class Authentication::Pharmacies::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :pharmacy_name,
      :pharmacy_phone_number,
      :pharmacy_owner_first_name,
      :pharmacy_owner_last_name,
      :email,
      :password
    ])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
  
  def after_sign_up_path_for(resource)
    pharmacy_dashboard_path
  end
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/main/pages_controller.rb
class Main::PagesController < ApplicationController
    
    def patients
        
    end
    
end

app/controllers/main/patients_controller.rb
class Main::PatientsController < ApplicationController
    
end

app/controllers/main/pharmacies_controller.rb
class Main::PharmaciesController < ApplicationController
  include Notifier
  before_action :set_pharmacy
  before_action :load_requests
  
  def dashboard
  end

  def edit
  end

  def update
    current_pharmacy.update pharmacy_params
    
    respond_to do |format|
      format.html { redirect_to :back, notice: "Changes saved!" }
    end
  end
  
  def status_requests
    @unresolved_requests = @patient_alerts.status_requests.unresolved
    @resolved_requests = @patient_alerts.status_requests.resolved
  end
  
  def refill_requests
    @unresolved_requests = @patient_alerts.refill_requests.unresolved
    @resolved_requests = @patient_alerts.refill_requests.resolved
  end
  
  def update_rx_status
    @alert = PatientAlert.find_by(evaluation_number: params[:eval_num])
    @alert.update(status: params[:status], resolved: true)
    
    respond_to do |format|
      format.js { render :layout => false, notice: "Update sent!" }
      
      ## send update
      TwilioHandler.alert_mobile_client(@alert)
    end
  end
  
  def load_chart
    @period = params[:period]
    render :layout => false
  end
  
  private
  
  def set_pharmacy
    @pharmacy = current_pharmacy
  end
  
  def load_requests
    @pharmacy = set_pharmacy
    @patient_alerts = current_pharmacy.patient_alerts.order('created_at DESC')
  end
  
  def pharmacy_params
    params.require(:pharmacy)
    .permit(
      :pharmacy_name,
      :pharmacy_phone_number,
      :pharmacy_owner_first_name,
      :pharmacy_owner_last_name)
  end
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
    
    def alerts
        current_pharmacy.patient_alerts
    end
    
    def alerts_received
        alerts.count
    end
    
    def alerts_resolved
        alerts.resolved.count
    end
    
    def response_rate
        rate = (alerts_resolved.to_f/alerts_received * 100).round(2)
        if rate.nan?
            return "0.00%"
        end
        return rate.to_s
    end
    
    def responsiveness
        ## for each alert
        ## => time += subtract(time_responded, time_received)
        ## end
        ## return time/total_alerts
        time = 0
        alerts.each do |a|
            time += (a.updated_at - a.created_at).to_i
        end
        ((time.to_f/(alerts.size * 60))).round(2)
    end
    
end

app/views/main/pharmacies/_dashboard_body.html.erb
<section id="analytics-snapshot">
    <div class="card">
        <div class="card-body">
            <div class="row" id="snapshot-cards-row">
                <div class="card diff">
                    <div class="card-body">
                        <h6>
                            <i class="fas fa-receipt"></i> Received
                            <hr>
                        </h6>
                        <p>
                            <%= alerts_received %>
                        </p>
                    </div>
                </div>
            
                <div class="card diff">
                    <div class="card-body">
                        <h6>
                            <i class="fas fa-clipboard-check"></i> Resolved
                            <hr>
                        </h6>
                        <p>
                            <%= alerts_resolved %>
                        </p>
                    </div>
                </div>
            
                <div class="card diff">
                    <div class="card-body">
                        <h6>
                            <i class="fas fa-bolt"></i> Resp. Rate
                            <hr>
                        </h6>
                        <p>
                            <%= response_rate %>
                        </p>
                    </div>
                </div>
            
                <div class="card diff">
                    <div class="card-body">
                        <h6>
                            <i class="far fa-clock"></i> Responsivity
                            <hr>
                        </h6>
                        <p class="diff">
                            <%= responsiveness %>
                            <span class="hrs">
                                mns
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            
            <section id="chart-section">
                <div id="chart-box" class="chart-box active">
                    <%= render "main/pharmacies/charts/day" %>
                </div>
                
                <div id="chart-controls">
                    <ul class="nav justify-content-center">
                        <li class="nav-item">
                            <%= link_to load_chart_path(:period => "day"), id:"day", class:"nav-link active",
                                remote: true, onclick:"$('#chart-controls .nav-link.active').toggleClass('active');
                                        $(`#${this.id}`).toggleClass('active');
                                        $(`#${this.id}-chart`).toggleClass('active');" do %>
                                Day     
                            <% end %>
                        </li>
                        
                        <li class="nav-item">
                            <%= link_to load_chart_path(:period => "week"), id:"week", class:"nav-link",
                                remote: true, onclick:"$('#chart-controls .nav-link.active').toggleClass('active');
                                        $(`#${this.id}`).toggleClass('active');
                                        $(`#${this.id}-chart`).toggleClass('active');" do %>
                                Week    
                            <% end %>
                        </li>
                        
                        <li class="nav-item">
                            <%= link_to load_chart_path(:period => "month"), id:"month", class:"nav-link",
                                remote: true, onclick:"$('#chart-controls .nav-link.active').toggleClass('active');
                                        $(`#${this.id}`).toggleClass('active');
                                        $(`#${this.id}-chart`).toggleClass('active');" do %>
                                Month    
                            <% end %>
                        </li>
                        
                        <li class="nav-item">
                            <%= link_to load_chart_path(:period => "year"), id:"year", class:"nav-link",
                                remote: true, onclick:"$('#chart-controls .nav-link.active').toggleClass('active');
                                        $(`#${this.id}`).toggleClass('active');
                                        $(`#${this.id}-chart`).toggleClass('active');" do %>
                                Year     
                            <% end %>
                        </li>
                    </ul>
                </div>
            </section>
        </div>
    </div>
</div>

app/views/main/pharmacies/_form.html.erb
<%= form_for(@pharmacy, :html => { :id => "pharmacy-edit-form", :multipart => true }) do |f| %>
    <div class="field">
        <div class="row">
            <div class="col-lg-6">
                <label for="pharmacy_owner_first_name">First name</label>
                <%= f.text_field :pharmacy_owner_first_name, autofocus: true, autocomplete: "name",
                    class:"form-control", placeholder:"First name" %>
            </div>
            
            <div class="col-lg-6">
                <label for="pharmacy_owner_last_name">Last name</label>
                <%= f.text_field :pharmacy_owner_last_name, autofocus: true, autocomplete: "name",
                    class:"form-control", placeholder:"Last name" %>
            </div>
        </div>
    </div>
    
    <div class="field">
        <label for="pharmacy_name">Pharmacy name</label>
        <%= f.text_field :pharmacy_name, autofocus: true, autocomplete: "name",
            class:"form-control", placeholder:"Pharmacy name" %>
    </div>
    
    <div class="field">
        <label for="pharmacy_phone_number">Phone number</label>
        <%= f.text_field :pharmacy_phone_number, autofocus: true, autocomplete: "phone_number",
            class:"form-control", placeholder:"Phone number" %>
    </div>
  
    <div class="actions">
        <%= f.submit "Save changes", class:"btn btn-primary btn-block" %>
    </div>
<% end %>

app/views/main/pharmacies/dashboard.html.erb
<%= render "dashboard_body" %>

app/views/main/pharmacies/edit.html.erb
<section id="edit-pharmacy">        
    <div class="row">
        <div class="col-lg-4">
            <div class="card " id="settings-navigation-card">
                <div class="card-body">
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link cursor-pointer active" onclick="toggleNav(this, 'account')">
                                Account
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link cursor-pointer" onclick="toggleNav(this, 'notifications')">
                                Notifications
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link cursor-pointer" onclick="toggleNav(this, 'billing')">
                                Billing
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link cursor-pointer" href="/password/settings">
                                Security
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link cursor-pointer" onclick="toggleNav(this, 'help')">
                                Help
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-7 offset-md-1">
            <div class="card" id="settings-content-card">
                <div class="card-body">
                    <div id="tab-account" class="tab active">
                        <h5 class="text-center">Account Settings</h5>
                        <hr>
                        
                        <%= render "form" %>
                    </div>
                    
                    <div id="tab-notifications" class="tab">
                        <h5 class="text-center">Notification Settings</h5>
                        <hr>
                        
                        <p>
                            <span>
                                Screen notifications (required)
                            </span>
                            <label class="switch">
                                <input type="checkbox" id="screen-notifications"
                                    onclick="requestPermission(this)">
                                <span class="slider round"></span>
                            </label>
                        </p>
                        
                        <p>
                            <span>
                                Email notifications
                            </span>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </p>
                        
                        <p>
                            <span>
                                Promotional emails
                            </span>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </p>
                    </div>
                    
                    <div id="tab-billing" class="tab">
                        <h5 class="text-center">Billing Settings</h5>
                        <hr>
                    </div>
                    
                    <div id="tab-security" class="tab">
                        <h5 class="text-center">Security Settings</h5>
                        <hr>
                    </div>
                    
                    <div id="tab-help" class="tab">
                        <h5 class="text-center">Help Center</h5>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    toggleNav = (elem, tab) => {
        $('a.active, .tab.active').toggleClass('active');
        elem.classList.add('active');
        $(`#tab-${tab}`).toggleClass('active')
    };
    
    requestPermission = (elem) => {
        var checked = elem.getAttribute('checked');
        if (checked == null) { // previously unchecked. now checked
            askPermission();
        } else {
            // revoke permission
        }
    }
</script>

app/views/main/pharmacies/load_chart.js.erb
$('#chart-box').html(`
    <%= render "main/pharmacies/charts/#{@period}" %>
`);

app/views/main/pharmacies/refill_requests.html.erb
<section id="status-requests">
    <div class="row">
        <div class="col-lg-4">
            <div class="card box-shadow request-number">
                <div class="card-body">
                    <h5>New Requests</h5>
                    <hr>
                    <span>
                        <%= @unresolved_requests.size %>
                    </span>
                </div>
            </div>
            
            <div class="card box-shadow request-number">
                <div class="card-body">
                    <h5>Resolved</h5>
                    <hr>
                    <span>
                        <%= @resolved_requests.size %>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-lg-7 offset-lg-1">
            <% @unresolved_requests.each do |r| %>
                <div class="status-request-card diff card">
                    <div class="card-body">
                        <span>
                            rx #939292
                        </span>
                        <span>
                            <%= time_ago_in_words(r.created_at) + " ago" %>
                        </span>
                        <span>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    update rx status <i class="fas fa-angle-down"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/main/pharmacies/status_requests.html.erb
<section id="status-requests">
    <div class="row">
        <div class="col-lg-4">
            <div class="card box-shadow request-number">
                <div class="card-body">
                    <h5>New Requests</h5>
                    <hr>
                    <span>
                        <%= @unresolved_requests.size %>
                    </span>
                </div>
            </div>
            
            <div class="card box-shadow request-number">
                <div class="card-body">
                    <h5>Resolved</h5>
                    <hr>
                    <span>
                        <%= @resolved_requests.size %>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-lg-7 offset-lg-1">
            <% @unresolved_requests.each do |r| %>
                <div class="status-request-card diff card" id="request-<%= r.evaluation_number %>">
                    <div class="card-body">
                        <span>
                            rx #<%= r.evaluation_number %>
                        </span>
                        <span>
                            <%= time_ago_in_words(r.created_at) + " ago" %>
                        </span>
                        <span>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    update rx status <i class="fas fa-angle-down"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <%= link_to update_rx_status_path(:status => "received", :eval_num => r.evaluation_number), class:"dropdown-item", remote: true, method: :post do %>
                                        <i class="fas fa-circle blue"></i> rx received!
                                    <% end %>
                                    
                                    <%= link_to update_rx_status_path(:status => "prep", :eval_num => r.evaluation_number), class:"dropdown-item", remote: true, method: :post do %>
                                        <i class="fas fa-circle yellow"></i> rx is in prep!
                                    <% end %>
                                    
                                    <%= link_to update_rx_status_path(:status => "ready", :eval_num => r.evaluation_number), class:"dropdown-item", remote: true, method: :post do %>
                                        <i class="fas fa-circle green"></i> rx is ready!
                                    <% end %>
                                    
                                    <%= link_to update_rx_status_path(:status => "no-rx", :eval_num => r.evaluation_number), class:"dropdown-item", remote: true, method: :post do %>
                                        <i class="fas fa-circle red"></i> can't fill rx!
                                    <% end %>
                                </div>
                            </div>
                        </span>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/main/pharmacies/update.html.erb
<h1>Pharmacies#update</h1>
<p>Find me in app/views/pharmacies/update.html.erb</p>

app/views/main/pharmacies/update_rx_status.js.erb
console.log('updated alert to <%= @alert.status %>!');

$('#request-<%= @alert.evaluation_number %>').fadeOut().remove();